blank_issues_enabled: false
contact_links:
  - name: ✉️ Scrivi allo sviluppatore / Email the developer
    url: mailto:blackcornermail@gmail.com
    about: Per domande o segnalazioni private / For questions or private reports
